amcl:
  ros__parameters:
    use_sim_time: false

    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    base_frame_id: base_link
    odom_frame_id: odom
    global_frame_id: map

    scan_topic: scan
    min_particles: 500
    max_particles: 2000

    laser_max_range: 12.0
    laser_min_range: 0.15

    update_min_d: 0.2
    update_min_a: 0.2

    resample_interval: 1
    transform_tolerance: 0.2

    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
